// AUTO-GENERATED from knowledge/*.md - DO NOT EDIT DIRECTLY
// To update, edit files in knowledge/ and run: node scripts/ingest.mjs --sync-chunks

export interface KnowledgeChunk {
	id: string;
	category: 'academics' | 'policy' | 'directory' | 'campus';
	content: string;
}

export const KNOWLEDGE_CHUNKS: KnowledgeChunk[] = [
	{
		"id": "academics-programs-1",
		"category": "academics",
		"content": "## College of Computer Studies Overview\n- **Dean**: Haidee Galdo (formerly Riza Siega)\n- **Location**: Main Campus, 1st Floor, right side near the entrance, beside the staircase.\n- **Accreditation & Affiliations**: PAASCU Accredited, CEAP Member, CHED Recognized.\n- **Official Links**: [CCS Department Website](https://www.sjc.edu.ph/academics/college-of-computer-studies) | [SJC Student Portal](https://online.sjc.edu.ph/enrollment/?content=enrollment) | [SJC Moodle LMS](https://lms.sjc.edu.ph/login/index.php) | [CCS Facebook Page](https://www.facebook.com/profile.php?id=100083430218425)\n- **Degrees Offered**:\n  - Bachelor of Science in Information Technology (BSIT) - 4 Years\n  - Bachelor of Science in Computer Science (BSCS) - 4 Years\n  - Associate in Computer Technology (ACT) - 2 Years (Ladderized into BSIT/BSCS)"
	},
	{
		"id": "academics-programs-2",
		"category": "academics",
		"content": "## Admission & Program Entry Requirements\n- **College Admission Test (CAT) Cut-Off**: Incoming first-year students must obtain a passing rate of at least 75% on the CAT for direct entry into BSIT or BSCS.\n- **Ladderized Pathway for ACT**: Applicants with CAT scores below 75% are enrolled in the 2-Year Associate in Computer Technology (ACT) program. They may shift to BSIT or BSCS after the first semester provided they achieve a Grade Point Average (GPA) of at least 2.25.\n- **Prerequisites for 4th Year Standing**: No student may enroll in the 4th year without completing and passing all Physical Education subjects (PATHFit 1 to 4) and NSTP (NSTP 11 and 12).\n- **Theology Requirement for Graduation**: Candidates for graduation from a 4-year degree (BSIT, BSCS) must complete 24 units of Theology (8 sequential courses, 3 units each, from Theo 1a to Theo 4b)."
	},
	{
		"id": "academics-programs-3",
		"category": "academics",
		"content": "## Theology & Religious Studies Curriculum (24 Units / 8 Courses)\nSaint Joseph College is a Catholic educational institution under the Diocese of Maasin. All 4-year degree candidates in the College of Computer Studies (BSIT and BSCS) are required to complete **24 units of Theology** (8 sequential courses, 3 units each) as a mandatory requirement for graduation:\n| Course Code | Course Title | Year & Semester | Units |\n| :--- | :--- | :--- | :--- |\n| **Theo 1a** | Old Testament | 1st Year — 1st Semester | 3 |\n| **Theo 1b** | New Testament | 1st Year — 2nd Semester | 3 |\n| **Theo 2a** | Christology | 2nd Year — 1st Semester | 3 |\n| **Theo 2b** | Mariology | 2nd Year — 2nd Semester | 3 |\n| **Theo 3a** | Christian Morality | 3rd Year — 1st Semester | 3 |\n| **Theo 3b** | The Commandments | 3rd Year — 2nd Semester | 3 |\n| **Theo 4a** | Introduction to Pastoral Life / Basic Ecclesial Communities (BEC) | Summer Term (Incoming 4th Year) | 3 |\n| **Theo 4b** | Pastoral Exposure | 4th Year — 1st Semester | 3 |\n\n*Note: Theology courses must be taken in sequence (Theo 1a through Theo 4b). Completion of all 24 units is strictly required for graduation clearance.*"
	},
	{
		"id": "academics-programs-4",
		"category": "academics",
		"content": "## General Education (GE) & Institutional Requirements\nAll undergraduate degree programs in CCS include the standard CHED General Education and institutional mandated subjects:\n| Course Code | Course Title | Description / Focus | Units |\n| :--- | :--- | :--- | :--- |\n| **GE 1** | Understanding the Self | Identity, psychology, self-development | 3 |\n| **GE 2** | Readings in Philippine History | Historical documents and national perspective | 3 |\n| **GE 3** | Mathematics in the Modern World | Practical mathematical tools and statistics | 3 |\n| **GE 4** | Purposive Communication | Professional, multimodal writing and speaking | 3 |\n| **GE 5** | Science, Technology, and Society (STS) | Impact of technology on human society | 3 |\n| **GE 6** | The Contemporary World | Globalization and international systems | 3 |\n| **GE 7** | Art Appreciation | Visual, musical, and performing arts | 3 |\n| **GE 8** | Ethics | Moral philosophy and decision making | 3 |\n| **GE 9** | Life and Works of Rizal | Mandated study of Dr. Jose Rizal | 3 |\n| **GE EL 1** | Living in the IT Era | Information literacy and digital tools | 3 |\n| **GE EL 2** | Gender and Society | Gender equality and social dynamics | 3 |\n| **GE EL 3** | Great Books | World literature and classical philosophy | 3 |\n| **PATHFit 1–4**| Physical Activities Toward Health and Fitness | Movement, Fitness, Sports, Dance (2 units each) | 8 |\n| **NSTP 11 & 12**| National Service Training Program | Civic Welfare / ROTC training (3 units each) | 6 |"
	},
	{
		"id": "academics-programs-5",
		"category": "academics",
		"content": "## Bachelor of Science in Information Technology (BSIT) Overview\n- **Duration**: 4 Years (8 Semesters + 1 Summer Term)\n- **Specialization / Focus**: Business Analytics, Systems Integration, Web Systems (HTML, CSS, JavaScript, PHP with XAMPP, SQL, Python/Django in 3rd Year), Networking, Cybersecurity, and Enterprise Data Management.\n- **Total Units**: ~167 Units\n- **Overview**: Prepares students for careers in software engineering, database administration, system integration, analytics, and network infrastructure."
	},
	{
		"id": "academics-programs-6",
		"category": "academics",
		"content": "## BSIT 1st Year Curriculum\n- **1st Year — 1st Semester (26 Units | 9 Subjects)**:\n  - IT 101: Introduction to Computing (3 units)\n  - IT 102: Computer Programming 1 (3 units)\n  - Math En: Math Enrichment (3 units)\n  - GE 1: Understanding the Self (3 units)\n  - GE 2: Readings in the Philippine History (3 units)\n  - GE EL 1: Living in the IT Era (3 units)\n  - Theo 1a: Old Testament (3 units)\n  - PATHFit 1: Movement Competency Training (2 units)\n  - NSTP 11: National Service Training Program 1 (3 units)\n- **1st Year — 2nd Semester (29 Units | 10 Subjects)**:\n  - IT 111: Networks and Communications 1 (3 units)\n  - IT 112: Computer Programming 2 (3 units)\n  - IT 113: Discrete Structures (3 units)\n  - GE 3: Mathematics in the Modern World (3 units)\n  - GE 4: Purposive Communication (3 units)\n  - GE 5: Science, Technology, and Society (3 units)\n  - GE EL 2: Gender and Society (3 units)\n  - Theo 1b: New Testament (3 units)\n  - PathFit 2: Exercise-based Fitness Activities (2 units)\n  - NSTP 12: National Service Training Program 2 (3 units)"
	},
	{
		"id": "academics-programs-7",
		"category": "academics",
		"content": "## BSIT 2nd Year Curriculum\n- **2nd Year — 1st Semester (26 Units | 9 Subjects)**:\n  - IT 201: Information Management (3 units)\n  - IT 202: Data Structures & Algorithms (3 units)\n  - IT 203: Web Systems and Technologies 1 (3 units)\n  - IT 204: Platform Technologies (3 units)\n  - GE 6: The Contemporary World (3 units)\n  - GE 7: Art Appreciation (3 units)\n  - GE EL 3: Great Books (3 units)\n  - Theo 2a: Christology (3 units)\n  - PathFit 3: Sports (2 units)\n- **2nd Year — 2nd Semester (26 Units | 9 Subjects)**:\n  - IT 211: Object - Oriented Programming (3 units)\n  - IT 212: Human Computer Interaction (3 units)\n  - IT 213: Application Dev & Emerging Tech (3 units)\n  - IT 214: Information Management 2 (3 units)\n  - IT 215: Systems Analysis and Design (3 units)\n  - GE 8: Ethics (3 units)\n  - GE 9: Life and Works of Rizal (3 units)\n  - Theo 2b: Mariology (3 units)\n  - PathFit 4: Dance (2 units)"
	},
	{
		"id": "academics-programs-8",
		"category": "academics",
		"content": "## BSIT 3rd Year & Summer Term Curriculum\n- **3rd Year — 1st Semester (24 Units | 8 Subjects)**:\n  - IT 301: Information Assurance and Security (3 units)\n  - IT 302: Systems Integration and Architecture 1 (3 units)\n  - IT 303: Networking 2 (3 units)\n  - IT 304: Quantitative Methods (3 units)\n  - IT 305: Web Systems and Technologies 2 (3 units)\n  - IT 306: Business Analytics (3 units)\n  - IT 307: Enterprise Data Management (3 units)\n  - Theo 3a: Christian Morality (3 units)\n- **3rd Year — 2nd Semester (24 Units | 8 Subjects)**:\n  - IT 311: Analytic Tools and Techniques (3 units)\n  - IT 312: Analytics Modeling (3 units)\n  - IT 313: Social Issues and Professional Practice (3 units)\n  - IT 314: Systems Admin and Maintenance (3 units)\n  - IT 315: Integrative Programming and Tech 1 (3 units)\n  - IT EL 1: IT Elective 1 (3 units)\n  - IT EL 2: IT Elective 2 (3 units)\n  - Theo 3b: The Commandments (3 units)\n- **Summer Term (Incoming 4th Year | 6 Units)**:\n  - Capstone 1: Capstone Project 1 (3 units)\n  - Theo 4a: Intro to Pastoral Life / BEC (3 units)"
	},
	{
		"id": "academics-programs-9",
		"category": "academics",
		"content": "## BSIT 4th Year Curriculum & Internship\n- **4th Year — 1st Semester (21 Units | 7 Subjects)**:\n  - Capstone 2: Capstones Project 2 (3 units)\n  - IT 401: Technopreneurship (3 units)\n  - IT 402: Analytics Application (3 units)\n  - Pro En: Professional Enhancement (3 units, held in Bonzel Hall)\n  - IT EL 3: IT Elective 3 (3 units)\n  - IT EL 4: IT Elective 4 (3 units)\n  - Theo 4b: Pastoral Exposure (3 units)\n- **4th Year — 2nd Semester (6 Units | 1 Subject)**:\n  - IT 403: IT Internship / On-the-Job Training (486 hrs) (6 units)"
	},
	{
		"id": "academics-programs-10",
		"category": "academics",
		"content": "## Bachelor of Science in Computer Science (BSCS) Overview & Curriculum\n- **Duration**: 4 Years (8 Semesters + 1 Summer Term)\n- **Description**: Emphasizes algorithms, computational theory, artificial intelligence, software engineering, and mathematical structures.\n- **Entry & Retention**: Requires at least 75% on the CAT and maintenance of a 2.25 GWA in 1st and 2nd year professional computing subjects for admission to 3rd year.\n- **Degree Culmination**: Original CS Computing Research / Thesis Project.\n- **Curriculum Highlights by Year**:\n  - **1st Year**: Introduction to Computing (CS 101), Computer Programming 1 & 2 (CS 102/112), Discrete Structures (CS 113), GE Subjects, Theo 1a (Old Testament), Theo 1b (New Testament), PATHFit 1 & 2, NSTP 11 & 12.\n  - **2nd Year**: Data Structures & Algorithms (CS 201), Object-Oriented Programming (CS 202), Computer Organization & Architecture, Automata Theory and Formal Languages, Theo 2a (Christology), Theo 2b (Mariology), PATHFit 3 & 4.\n  - **3rd Year**: Design & Analysis of Algorithms, Operating Systems, Software Engineering 1 & 2, Programming Languages, Artificial Intelligence, Theo 3a (Christian Morality), Theo 3b (The Commandments), CS Thesis / Capstone 1 & Theo 4a (Summer).\n  - **4th Year — 1st Semester**: CS 401: CS Capstone Project 2 (3 units), CS 402: Social Issues and Professional Practice (3 units), CS Elective 2 (3 units), Theo 4b: Pastoral Exposure (3 units).\n  - **4th Year — 2nd Semester**: CS 403: Practicum / Industry Internship (500 hrs) (6 units)."
	},
	{
		"id": "academics-programs-11",
		"category": "academics",
		"content": "## Associate in Computer Technology (ACT)\n- **Duration**: 2 Years (4 Semesters, Ladderized)\n- **Total Units**: 53 Units\n- **Description**: Equips students with foundational computing skills, hardware servicing, office productivity, and programming fundamentals.\n- **Ladderization**: Students completing the 2-year curriculum or reaching a 2.25 GPA after 1st sem can transition seamlessly into the 3rd year of BSIT or BSCS.\n- **Curriculum by Year & Semester**:\n  - **1st Year — 1st Semester (17 Units | 6 Subjects)**:\n    - ACT 101: Introduction to Computing & Hardware (3 units)\n    - ACT 102: Computer Logic & Programming 1 (3 units)\n    - GE 1: Understanding the Self (3 units)\n    - GE 3: Mathematics in the Modern World (3 units)\n    - PATHFIT 1: Movement Competency Training (2 units)\n    - NSTP 11: National Service Training Program 1 (3 units)\n  - **1st Year — 2nd Semester (14 Units | 5 Subjects)**:\n    - ACT 103: Computer Programming 2 (3 units)\n    - ACT 104: PC Maintenance & Troubleshooting (3 units)\n    - GE 4: Purposive Communication (3 units)\n    - PATHFIT 2: Fitness Activities (2 units)\n    - NSTP 12: National Service Training Program 2 (3 units)\n  - **2nd Year — 1st Semester (11 Units | 4 Subjects)**:\n    - ACT 201: Web Development Essentials (3 units)\n    - ACT 202: Networking Fundamentals (3 units)\n    - ACT 203: Database Management Systems (3 units)\n    - PATHFIT 3: Sports Competency (2 units)\n  - **2nd Year — 2nd Semester (11 Units | 3 Subjects)**:\n    - ACT 204: Systems Integration Project (3 units)\n    - ACT 205: Technical Internship (300 Hours) (6 units)\n    - PATHFIT 4: Outdoor Fitness (2 units)"
	},
	{
		"id": "policy-academic_policies-1",
		"category": "policy",
		"content": "## College of Computer Studies Retention & Academic Standing\n- **Admission to 3rd Year BSIT / BSCS**: Students must complete all prescribed 1st and 2nd year professional computing courses with an average rating of at least **2.25**. This 2.25 average rating must be maintained.\n- **Failing Limit & Shifting**: Any student who fails in more than three (3) subjects shall be advised to shift to another course.\n- **CAT Entrance Threshold**: Passing rate of 75% on College Admission Test (CAT) is required for BSIT/BSCS; below 75% enters 2-year ACT and can shift after 1st sem with a 2.25 GPA.\n- **Fourth Year Prerequisite Gate**: No student is allowed to enroll in the 4th year unless all Physical Education courses (PATHFit 1, 2, 3, 4) and NSTP (NSTP 11 and 12) have been successfully passed.\n- **Theology Requirement**: All candidates graduating from a 4-year program must complete 24 units of Theology (Theo 1a to Theo 4b)."
	},
	{
		"id": "policy-academic_policies-2",
		"category": "policy",
		"content": "## Tuition, Laboratory Fees & Semestral Cost Structure\nThe Finance & Bursar's Office assesses tuition and laboratory fees per semester based on enrolled academic and laboratory units:\n- **Tuition Fee Rate**: **₱524.00 per unit** (~**₱1,572.00** per standard 3-unit subject).\n- **Semestral Tuition Estimate**: Ranges from **₱11,000 to ₱14,300 per semester** (depending on academic unit load, typically 21 to 29 units per semester).\n- **Laboratory Fees**: **₱1,262.00 per laboratory course** (e.g., Programming, Web Systems, Networking, Database, Capstone Project 2, and IT Electives).\n- **Itemized Miscellaneous & Institutional Fees**:\n  - **LMS (Learning Management System / Moodle)**: ₱750.00\n  - **Registration Fee**: ₱660.00\n  - **Library Fee**: ₱299.00\n  - **Energy Fee**: ₱250.00\n  - **PRISAA Fee**: ₱200.00\n  - **Medical & Dental Fee**: ₱188.00\n  - **Research & Extension**: ₱150.00\n  - **Printings / Departmental Materials**: ₱150.00\n  - **Spiritual Services & Retreat**: ₱1,425.00\n  - **Loyalty Day**: ₱450.00\n  - **PAASCU & CEAP Membership**: ₱75.00\n  - **Student Organization (PSITS / FCSO)**: ₱56.00\n  - **Acquaintance Party & Socials**: ₱40.00\n- **Fee Assessment & Payment**: Evaluated and issued at the Finance & Bursar's Office (Ground Floor, Admin Building). Examination permits are issued upon partial or full semestral settlements."
	},
	{
		"id": "policy-academic_policies-3",
		"category": "policy",
		"content": "## Scholarships, Discounts, and Special Privileges\n- **Academic Scholarships (Semestral GWA)**:\n  - **Full Tuition (100%)**: GWA 1.00 – 1.20 (no grade below 1.25)\n  - **Three-Fourths Tuition (75%)**: GWA 1.21 – 1.40 (no grade below 1.50)\n  - **Half Tuition (50%)**: GWA 1.41 – 1.60 (no grade below 1.75)\n  - **Dean's Lister Honor Roll**: GWA 1.61 – 1.80 (no grade below 2.00, full load, no NC/FA/FW)\n- **Diocesan & Institutional Discounts**:\n  - **Alumni of Diocesan Schools**: **70% discount**\n  - **Alumni of Private Schools in Diocese of Maasin (Josephinian Grant)**: **50% discount**\n  - **Residents of Sogod, Baybay, and beyond**: **40% discount**\n  - **SJC Senior High School Alumni**: **20% discount**\n  - **Family Discount**: 3 siblings = 5% each; 4 siblings = 7% each; 5+ siblings = 10% each on tuition\n  - **Student Leaders**: President of FCSO (100% full tuition); Editors of \"The Josephinian\" (Full or 50% discount)\n  - **Government Subsidies**: DOST-SEI, CHED Grants, UniFAST / Tertiary Education Subsidy (TES)"
	},
	{
		"id": "policy-academic_policies-4",
		"category": "policy",
		"content": "## Step-by-Step Enrollment & Registration Workflow\n1. **Step 1 — Admissions & CAT Screening (Registrar's Office, Ground Floor Admin Bldg)**:\n   - Submit entrance credentials: Form 138/SF9, Certificate of Good Moral Character, PSA Birth Certificate (or TOR & Honorable Dismissal for transferees) and take the College Admission Test (CAT).\n2. **Step 2 — CCS Academic Evaluation & Advising (CCS Dean's Office, 1st Floor Main Campus)**:\n   - Meet with Dean Haidee Galdo or program heads for evaluation of CAT scores (75% threshold) and curriculum advising.\n3. **Step 3 — Subject Advising & Portal Encoding (CCS Department / Student Portal)**:\n   - Select and encode prescribed semester subjects on the [SJC Student Portal](https://online.sjc.edu.ph/enrollment/?content=enrollment) adhering to prerequisites.\n4. **Step 4 — Fee Assessment & Settlement (Finance & Bursar's Office, Ground Floor Admin Bldg)**:\n   - Receive tuition and lab fee assessment slip. Settle downpayment/tuition or present scholarship grant vouchers (Josephinian 50%, UniFAST/TES, CHED, DOST).\n5. **Step 5 — Official Registration & COR Stamping (Registrar's Office & Cashier)**:\n   - Claim validated and stamped Certificate of Registration (COR) and student ID validation."
	},
	{
		"id": "policy-academic_policies-5",
		"category": "policy",
		"content": "## Official Grading Scale & Equivalents\n- **1.00** = 98% and above (Excellent - Summa Cum Laude interval)\n- **1.25** = 95% - 97% (Very Good)\n- **1.50** = 92% - 94% (Very Good - Magna Cum Laude interval)\n- **1.75** = 89% - 91% (Good - Cum Laude interval)\n- **2.00** = 86% - 88% (Good - Dean's Lister interval)\n- **2.25** = 83% - 85% (Good - CCS 3rd Year Retention Threshold)\n- **2.50** = 80% - 82% (Fair)\n- **2.75** = 77% - 79% (Fair)\n- **3.00** = 75% - 76% (Passed / Minimum Passing Grade)\n- **5.00** = Below 75% (Failed)\n- **NC** = No Credit (Given when final exam is missed and standing is unsatisfactory; compliance window within 2 weeks after rating sheet submission)\n- **W** = Officially Withdrawn (Complied with official withdrawal processing)\n- **FW** = Failure due to Unofficial Withdrawal (Stopped attending without official notice)\n- **FA** = Failure due to Excessive Absences (Exceeded maximum allowed class absences)"
	},
	{
		"id": "policy-academic_policies-6",
		"category": "policy",
		"content": "## Attendance, Absences, and Exam Rules\n- **Tardiness & Absences**: Arriving 15 minutes late, leaving 15 minutes early, or accumulating 3 consecutive tardiness marks counts as 1 absence.\n- **Maximum Absences (FA Drop)**: Incurring 10 absences in full in-person classes (or 5 absences in HyFlex/flexible modality) results in automatic drop with a permanent rating of \"FA\".\n- **Major Examinations**: Administered 4 times per semester: Pre-midterm, Midterm, Prefinal, and Final examinations. Students must present an official Examination Permit issued by the Bursar's / Cashier Office. Special exams must be filed with the Dean within 5 days with valid medical/justifiable proof."
	},
	{
		"id": "policy-academic_policies-7",
		"category": "policy",
		"content": "## Uniform, Attire & Dress Code Guidelines\n- **Regular Days (Mon, Tue, Thu, Fri)**: Prescribed customized SJC uniform. Males: SJC polo, pants, white undershirt, black leather shoes, clean haircut (no long/colored hair, no piercings/earrings). Females: SJC blouse, skirt at least 2 inches below the knee or straight-cut pants, closed black shoes.\n- **Wash Days (Wednesdays & Saturdays)**:\n  - **Wednesdays**: Old or New CCS Departmental Polo Shirt.\n  - **Saturdays**: Departmental or Recognized Organization Polo Shirt, or decent semi-formal/formal attire covering knees (Catholic school modesty guidelines).\n- **Internship / OJT**: Prescribed official Intern Uniform while on duty and within campus premises."
	},
	{
		"id": "directory-faculty_and_staff-1",
		"category": "directory",
		"content": "## CCS Faculty & Staff Directory Overview\n- **College of Computer Studies (CCS)**: Established in 1994 at Saint Joseph College (SJC, founded 1928 in Maasin City, Southern Leyte).\n- **CCS Department Motto**: \"An open door to the limitless horizon\"\n- **SJC Institutional Motto**: \"Deus, Patria, Scientia\" (God, Country, Knowledge) - Pax 1928.\n- **Dean & BSIT Program Head**: Mrs. Haidee T. Galdo, MIT (Dean's Office: Main Campus, 1st Floor right side near entrance beside staircase).\n- **Department Secretary**: Mrs. Wilna Mae Quilla-Oberez, MBA (Department secretary from 2013 to present).\n- **Faculty Excellence**: Experienced educators and industry practitioners holding advanced master's degrees (MIT, MBA, MST-CS), PhilNITS IT Passport certifications, MikroTik network certifications, and Civil Service eligibilities."
	},
	{
		"id": "directory-faculty_and_staff-2",
		"category": "directory",
		"content": "## Mrs. Haidee T. Galdo, MIT (CCS Dean & BSIT Program Head)\n- **Position / Title**: Dean, College of Computer Studies (CCS); Program Head for BSIT; College Faculty.\n- **Undergraduate Degree**: BS Computer Science — Southwestern University (SWU), Cebu City.\n- **Post-Graduate Degree**: Master in Information Technology (MIT) — Asian Development Foundation College (ADFC) / Asian College Foundation.\n- **Subjects Handled**:\n  - Data Structures and Algorithms (IT 202)\n  - Computer Programming (Java / IT 102 & IT 112)\n  - Algorithm and Complexity (CS)\n  - Science, Technology, and Society (GE 5 / STS)\n  - Capstone Project 2 (Capstone 2)\n- **Certifications**: PhilNITS IT Passport Exam Certified.\n- **Office Location & Consultation**: Main Campus, 1st Floor, right side near the entrance, beside the staircase. Available during regular office hours (Monday–Friday, 8:00 AM – 5:00 PM) for academic advising, curriculum evaluations, and student consultations."
	},
	{
		"id": "directory-faculty_and_staff-3",
		"category": "directory",
		"content": "## Mrs. Evangeline E. Javier, MIT (Senior College Faculty & Religious Org Adviser)\n- **Position / Title**: College Faculty (over 20 years of college faculty teaching experience at SJC); Departmental Religious Organization Adviser.\n- **Undergraduate Degree**: BS Computer Science — Saint Joseph College (SJC), Maasin City.\n- **Post-Graduate Degree**: Master in Information Technology (MIT) — Asian Development Foundation College (ADFC).\n- **Subjects Handled**:\n  - Business Analytics (IT 306)\n  - Enterprise Data Management (IT 307)\n  - Systems Integration and Architecture 1 (IT 302)\n  - Introduction to Computing (IT 101)\n  - Science, Technology, and Society (GE 5 / STS)\n  - Analytics Application (IT 402)\n  - Information Management (IT 201)\n- **Certifications**: MikroTik Network Certified (Networking), PhilNITS IT Passport Exam Certified."
	},
	{
		"id": "directory-faculty_and_staff-4",
		"category": "directory",
		"content": "## Mrs. Yvonne Tenio, MIT (College Faculty)\n- **Position / Title**: College Faculty — Saint Joseph College CCS Department.\n- **Undergraduate Degree**: BS Computer Science — University of San Jose - Recoletos (USJ-R), Cebu City.\n- **Post-Graduate Degree**: Master in Information Technology (MIT) — Asian Development Foundation College (ADFC).\n- **Subjects Handled**:\n  - IT 204: Platform Technologies\n  - IT 304: Quantitative Methods\n  - IT EL 3: IT Elective 3\n  - IT 301: Information Assurance and Security\n  - GE 5: Science, Technology, and Society (STS)\n  - GE EL 1: Living in the IT Era\n- **Certifications & Eligibilities**:\n  - Civil Service Commission (CSC) Certificate of Eligibility: Career Service Professional & Career Service Sub-Professional\n  - Quipper Faculty Training Certified\n  - PhilNITS IT Passport Exam Certified"
	},
	{
		"id": "directory-faculty_and_staff-5",
		"category": "directory",
		"content": "## Mr. Marnuld F. Climaco, MST-CS (Senior Computer Instructor)\n- **Position / Title**: Computer Instructor (serving Saint Joseph College from 1998 to present).\n- **Undergraduate Degree**: BS Computer Science — University of San Jose - Recoletos (USJ-R), Cebu City.\n- **Post-Graduate Degree**: Master of Science in Teaching - Major in Computer Science (MST-CS) / MIT.\n- **Industry & Teaching Experience**:\n  - Computer Operator (1994–1995, Philphos, Isabel, Leyte)\n  - Computer Instructor (1996–1997, College of Maasin)\n  - Computer Instructor (1997–1998, Southern Leyte Computer Institute)\n  - Computer Instructor (1998–present, Saint Joseph College)\n- **Subjects Handled**:\n  - Computer Computing / Introduction to Computing (IT 101 / ACT 101)\n  - Networking (IT 111 / IT 303 / ACT 202)\n  - Human Computer Interaction (IT 212 / HCI)\n  - Systems Administration and Maintenance (IT 314)\n- **Certifications**: MikroTik Network Certified (Networking), PhilNITS IT Passport Exam Certified."
	},
	{
		"id": "directory-faculty_and_staff-6",
		"category": "directory",
		"content": "## Mr. Leonardo E. Hoyla (Instructor, EDP Head & Portal Developer)\n- **Position / Title**: Computer Instructor; System Software Developer; Head of EDP (Electronic Data Processing) at Saint Joseph College.\n- **Motto / Slogan**: \"An open door to the limitless horizon\"\n- **Undergraduate Education**: BS Computer Science — Southwestern University (SWU); Nautical — Philippine Merchant Marine School (PMMS).\n- **Industry & Developer Experience**:\n  - System Software Developer — University of Cebu\n  - Management Information System (MIS) — Prince Warehouse Clubs\n  - Data Controller — Data Solutions Incorporated\n  - System Software Developer & EDP Head — Saint Joseph College\n- **Key Institutional Achievement**: Core developer of the official Saint Joseph College Portal ([SJC Student Portal](https://online.sjc.edu.ph/enrollment/?content=enrollment)).\n- **Subjects Handled**:\n  - Computer Programming (Java, PHP, Visual Basic)\n  - Web Systems and Technologies (IT 203 / IT 305)\n- **Certifications**: Visual Basic Certified (Southwestern University); SOLAS (Safety of Life at Sea) Certified (PMMS)."
	},
	{
		"id": "directory-faculty_and_staff-7",
		"category": "directory",
		"content": "## Mr. Jonathan F. Tse, MBA (Faculty & IT Certification Reviewer)\n- **Position / Title**: College Faculty / IT Certification Reviewer; Businessman (Properties of Evergreen General Merchandise).\n- **Undergraduate Degree**: BS Computer Engineering — University of San Carlos (USC), graduated Magna Cum Laude.\n- **Post-Graduate Degree**: Master of Business Administration (MBA) — Ateneo Graduate School of Business.\n- **Industry & Corporate Background**: Nearly 20 years in software development leadership with a Japanese technology company, culminating as Vice President for Cebu Operations.\n- **Community & Institutional Leadership**: President of SJC Alumni Foundation (served 3 years); Chief of Staff of Rotary International District 3860.\n- **Outstanding Achievement**: PhilNITS IT Passport Exam — Scored highest among 1,612 examinees across all 6 IT PEC countries.\n- **Subjects Handled**: IT Certification Exam Review (PhilNITS & IT certifications)."
	},
	{
		"id": "directory-faculty_and_staff-8",
		"category": "directory",
		"content": "## CCS Technical Staff, Department Secretary & Support Officers\n- **Mrs. Wilna Mae Quilla-Oberez, MBA**: Department Secretary of the College of Computer Studies from 2013 to present. Educational background: BS in Business Administration major in Financial Management; Master in Business Administration (MBA). Handles departmental communications, student inquiries, faculty scheduling, and administrative records.\n- **Mr. Nelson Garde**: Head Technician / Solar Manager. Oversees campus technical maintenance, laboratory hardware reliability, and solar infrastructure.\n- **Mr. Anthony Ejercito**: Head IT Technical Staff. Educational background: BS Computer Science. Manages technical operations and hardware maintenance for computer labs.\n- **Mr. Noel Buenasaga**: Assistant IT Technical Staff & Instructor. Educational background: BS Computer Science (Saint Joseph College). Subjects handled: CS Elective, System Fundamentals, Network Management.\n- **Mr. Angelo Cortel**: Part-time Teacher / Instructor. Educational background: BS Information Technology (Saint Joseph College). Subjects handled: Web Systems and Technologies 2 (IT 305).\n- **Ms. Dandielle Fate Monter**: Computer Instructor (\"An open door to the limitless horizon\").\n- **Mr. Joseph Demiao**: School Information Technology Officer (SITO) (\"An open door to the limitless horizon\"). Manages institutional network access, portal technical support, and campus IT infrastructure."
	},
	{
		"id": "directory-offices-1",
		"category": "directory",
		"content": "## CCS Leadership, Dean's Office & Department Staff\n- **Dean of CCS & Program Head BSIT**: Mrs. Haidee T. Galdo, MIT (formerly Riza Siega)\n- **Department Secretary**: Mrs. Wilna Mae Quilla-Oberez, MBA (Department Secretary since 2013)\n- **Location**: Main Campus, 1st Floor, right side near the entrance, beside the staircase.\n- **Office Hours**: Regular work hours (Monday to Friday, 8:00 AM - 5:00 PM; availability based on schedule).\n- **Student Consultations**: Open for consultation anytime or by appointment.\n- **Services**: Academic advising, subject crediting, curriculum evaluation, department endorsements, special exam approvals, and student guidance.\n- **CCS Department Website**: [CCS Webpage](https://www.sjc.edu.ph/academics/college-of-computer-studies)\n- **Official CCS Facebook Page**: [CCS Facebook Page](https://www.facebook.com/profile.php?id=100083430218425)"
	},
	{
		"id": "directory-offices-2",
		"category": "directory",
		"content": "## Institutional Administration & Official Links\n- **School President**: Rev. Msgr. Oscar A. Cadayona, PhD, SThL-MA\n- **Institution**: Saint Joseph College (SJC, founded 1928; CCS founded 1994), Main Campus, Tunga-tunga, Maasin City, Southern Leyte, Philippines.\n- **Institutional Motto**: \"Deus, Patria, Scientia\" (God, Country, Knowledge) - Pax 1928.\n- **CCS Motto**: \"An open door to the limitless horizon\"\n- **Trunkline / Phone**: (053) 570 8448\n- **Official Institutional Email**: info@sjc.edu.ph\n- **Data Protection Officer**: dpo@sjc.edu.ph\n- **Official School Website**: [Saint Joseph College](https://www.sjc.edu.ph/)\n- **Official SJC Facebook Page**: [SJC Facebook](https://www.facebook.com/sjc2028)\n- **Student Portal (Enrollment & Grades)**: [SJC Student Portal](https://online.sjc.edu.ph/enrollment/?content=enrollment)\n- **SJC Moodle LMS (Online Learning Platform)**: [SJC Moodle LMS](https://lms.sjc.edu.ph/login/index.php)"
	},
	{
		"id": "directory-offices-3",
		"category": "directory",
		"content": "## Key Student Support & Administrative Offices\n- **Registrar & Admissions Office (Ground Floor, Admin Bldg)**:\n  - College Admission Test (CAT) processing, freshmen and transferee credential evaluation (Form 138/SF9, Good Moral, PSA Birth Certificate, TOR/Honorable Dismissal).\n  - Subject add/drop, official scholastic records, and stamped Certificate of Registration (COR).\n- **Finance & Bursar's Office (Ground Floor, Admin Bldg)**:\n  - Tuition assessment (₱524/unit or ~₱1,572 per 3-unit course), lab fee settlements (₱1,262 per lab), examination permits (Pre-mid, Midterm, Prefinal, Final), scholarship application credits (Diocesan 50%-70%, UniFAST/TES, CHED, DOST-SEI).\n- **Student Affairs and Services Office (SASO)**:\n  - Oversees student organizations (PSITS, FCSO), clearance for campus activities, student handbook compliance, and student welfare.\n- **Guidance & Placement Services**:\n  - Mandatory 1st year second-semester psychological evaluation, career placement, and personal counseling.\n- **Information & Orientation Services / SITO (School Information Technology Officer - Mr. Joseph Demiao)**:\n  - Campus network access, [SJC Student Portal](https://online.sjc.edu.ph/enrollment/?content=enrollment) access and troubleshooting, and computer lab room reservations."
	},
	{
		"id": "campus-facilities_and_life-1",
		"category": "campus",
		"content": "## Computer Laboratories & Campus Facilities\n- **Laboratories (4th Floor, Rooms 407–409)**: Fully air-conditioned computer laboratories equipped for programming, networking, database management, and systems administration.\n- **ILLC Laboratory (Ground Floor)**: Integrated Learning and Laboratory Center utilized for web development, emerging technologies, and systems integration courses.\n- **Bonzel Hall**: Multi-purpose auditorium/hall utilized for Professional Enhancement courses, tech symposiums, department assemblies, and major institutional events.\n- **Laboratory Usage & Policies**:\n  - Open during designated laboratory schedules and class hours.\n  - Working students and laboratory coordinators supervise equipment and logbook sign-ins.\n  - Food, open drinks, and tampering with network or desktop configurations are strictly prohibited."
	},
	{
		"id": "campus-facilities_and_life-2",
		"category": "campus",
		"content": "## Software Environment & Coding Tools\n- **Introductory Programming (1st & 2nd Year)**: Java developed primarily with **TextPad 7** (for foundational syntax, OOP, and data structures).\n- **Web & Database Development (2nd & 3rd Year)**: HTML5, CSS3, JavaScript, PHP, and SQL using the **XAMPP stack** (Apache & MySQL).\n- **Backend & Emerging Tech (3rd Year)**: **Python** and **Django framework** for advanced web development and data analytics.\n- **General IDEs & Editors**: **VS Code**, **Notepad++**, and database management interfaces.\n- **Operating Systems**: Windows 10 transitioning into Windows 11 enterprise configurations."
	},
	{
		"id": "campus-facilities_and_life-3",
		"category": "campus",
		"content": "## Student Laptop & Hardware Recommendations\n- **Requirement Status**: Not strictly mandatory for freshmen, but strongly encouraged by 3rd and 4th year for Capstone Projects and advanced development.\n- **Recommended Hardware**: Budget-friendly or secondhand laptops (e.g., Lenovo ThinkPad, Dell Latitude in the ₱18,000 - ₱30,000 range) capable of smoothly executing VS Code, NodeJS, and local server environments."
	},
	{
		"id": "campus-facilities_and_life-4",
		"category": "campus",
		"content": "## Student Organizations & Campus Life\n- **Department & Co-Curricular Orgs**:\n  - **College of Computer Studies (CCS) Student Body**: Departmental curricular organization.\n  - **Philippine Society of Information Technology Students (PSITS)**: Official co-curricular student organization recognized under SASO for computing majors.\n  - **Federation of College Student Organizations (FCSO)**: Apex student governing coalition.\n  - **The Josephinian**: Official campus student publication.\n- **Department Traditions & Annual Events**:\n  - **CCS Departmental Days & Tech Events**: Coding competitions, seminars, project showcases.\n  - **Acquaintance Party & Socials**: Department social orientation and team-building.\n  - **Loyalty Day & Family Run**: SJC institutional community traditions.\n  - **PRISAA Meet**: Inter-school athletic and cultural competitions."
	}
];
